<?php
// Copy this file to config.php and fill in real values.
// config.php is gitignored on purpose — never commit real database
// credentials to the repository. On the server, create config.php
// next to this file (it is not generated by the build).

define('DB_HOST', '127.0.0.1'); // 'localhost' makes PHP try a unix socket, which often isn't set up on shared hosting — use the TCP address instead
define('DB_PORT', 3306);
define('DB_NAME', '27596_vindex');
define('DB_USER', '27596_61186');
define('DB_PASS', 'UH.._45DcPS');
